# Generated by Django 5.2.8 on 2025-12-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'News Ticker',
                'verbose_name_plural': 'News Ticker',
                'ordering': ['-created_at'],
            },
        ),
    ]
